Sprint 3
veniameen/middle.messenger.praktikum.yandex pull request #2
Opened 2022-05-06 22:34 UTC by veniameen

2022-05-07 05:17 UTC, podlovchenko commented
Привет, нужно сначала смержить в ветку main пулл реквест по второму спринту, а потом обновить эту ветку через git rebase

2022-05-07 17:18 UTC, podlovchenko requested changes
Привет, в целом все хорошо, по работе системы есть замечания
Нет перенаправления на страницу чатов, если пользователь уже в системе
Не получилось обновить аватар
По ссылке сменить пароль открывается страница редактирования профиля, а не смены пароля
На нетлифае старая версия

2022-05-07 17:18 UTC, podlovchenko commented on src/views/chat-select/index.ts
> +    if (!message || message === '') {
''  и так приводится к false, достаточно условия !message

2022-05-07 17:18 UTC, podlovchenko commented on src/views/signup/template.ts
> +    // },
Не стоит оставлять закомментированый код

2022-05-07 17:18 UTC, podlovchenko commented on src/utils/splitTimestamp.ts
> +  const timeFull = datetime[1];
А если передан не правильный формат строки? Нужно добавить проверку

2022-05-07 17:18 UTC, podlovchenko commented on src/utils/isObject.ts
> +  return typeof instance === 'object' && instance !== null;
А если передать массив?

2022-05-07 17:18 UTC, podlovchenko commented on package.json
> +    "eslint": "./node_modules/.bin/eslint src/**/**/*.ts",
Почему не просто eslint?

2022-05-09 05:47 UTC, podlovchenko commented
Привет, еще пару замечаний
Не открывается форма регистрации по ссылке "нет аккаунта?"
Сообщения в чате видны только после обновления страницы
В остальном все окей, жду правок и приму работу)

2022-05-09 13:44 UTC, podlovchenko approved these changes
Работу принимаю

2022-05-09 13:44 UTC, podlovchenko commented on package.json
> +    "@babel/cli": "^7.17.10",
Стоит указывать фиксированные версии или добавлять package-lock.json, иначе переустановки пакетов могут возникнуть ошибку из-за разных версий, потому что с ^ устанавливается последняя минорная версия

2022-05-09 14:32 UTC, veniameen commented on package.json
> +    "@babel/cli": "^7.17.10",
Понял, спасибо!

2022-05-09 16:42 UTC, merged